spring.application.name=PuntoYComa
spring.datasource.url=jdbc:mysql://localhost:3306/puntoycoma_db
spring.datasource.username=root
spring.datasource.password=Tatengue44179958
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update